import React from 'react';
import './Privacy.css';



const PrivacyPolicy = () => {
    return (
        <div className="wrapper-privacy">
            <div className="wrapper-privacy-child">
                <div className={'header--wrapper-leaders'}>
                    <p className={'header--wrapper--text-leaders'}> PRIVACY POLICY</p>
                </div>
                <div>
                    <div>
                        <p>Effective date: 08/01/2020</p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>Introduction</strong>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            <span style={{ fontWeight: 400 }}>Welcome to&nbsp;</span>
                            <strong>Loanith</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                Loanith&nbsp;(“us”, “we”, or “our”) operates&nbsp;https://www.loanith.com
                                and Loanith mobile application&nbsp;(hereinafter referred to as “
    </span>
                            <strong>Service</strong>
                            <span style={{ fontWeight: 400 }}>”).</span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Our Privacy Policy governs your visit to&nbsp;https://www.loanith.com and
                                Loanith mobile application, and explains how we collect, safeguard and
                                disclose information that results from your use of our Service.&nbsp;
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                We use your data to provide and improve Service. By using Service, you
                                agree to the collection and use of information in accordance with this
                                policy. Unless otherwise defined in this Privacy Policy, the terms used in
                                this Privacy Policy have the same meanings as in our Terms and Conditions.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>Our Terms and Conditions (“</span>
                            <strong>Terms</strong>
                            <span style={{ fontWeight: 400 }}>
                                ”) govern all use of our Service and together with the Privacy Policy
                                constitutes your agreement with us (“
    </span>
                            <strong>agreement</strong>
                            <span style={{ fontWeight: 400 }}>”).</span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>
                                <strong>Definitions</strong>
                            </strong>
                        </p>
                        <p>
                            <strong>SERVICE&nbsp;</strong>
                            <span style={{ fontWeight: 400 }}>
                                means the&nbsp;https://www.loanith.com website and Loanith mobile
                                application&nbsp;operated by&nbsp;Loanith
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>PERSONAL DATA</strong>
                            <span style={{ fontWeight: 400 }}>
                                &nbsp;means data about a living individual who can be identified from
                                those data (or from those and other information either in our possession
                                or likely to come into our possession).
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>USAGE DATA</strong>
                            <span style={{ fontWeight: 400 }}>
                                &nbsp;is data collected automatically either generated by the use of
                                Service or from Service infrastructure itself (for example, the duration
                                of a page visit).
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>COOKIES</strong>
                            <span style={{ fontWeight: 400 }}>
                                &nbsp;are small files stored on your device (computer or mobile device).
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>DATA CONTROLLER</strong>
                            <span style={{ fontWeight: 400 }}>
                                &nbsp;means a natural or legal person who (either alone or jointly or in
                                common with other persons) determines the purposes for which and the
                                manner in which any personal data are, or are to be, processed. For the
                                purpose of this Privacy Policy, we are a Data Controller of your data.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong>
                            <span style={{ fontWeight: 400 }}>
                                &nbsp;means any natural or legal person who processes the data on behalf
                                of the Data Controller. We may use the services of various Service
                                Providers in order to process your data more effectively.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>DATA SUBJECT&nbsp;</strong>
                            <span style={{ fontWeight: 400 }}>
                                is any living individual who is the subject of Personal Data.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>THE USER&nbsp;</strong>
                            <span style={{ fontWeight: 400 }}>
                                is the individual using our Service. The User corresponds to the Data
                                Subject, who is the subject of Personal Data.
    </span>
                        </p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>Information Collection and Use</strong>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                We collect several different types of information for various purposes to
                                provide and improve our Service to you.
    </span>
                        </p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>Types of Data Collected</strong>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            &nbsp;<strong>Personal Data</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                While using our Service, we may ask you to provide us with certain
                                personally identifiable information that can be used to contact or
                                identify you (“
    </span>
                            <strong>Personal Data</strong>
                            <span style={{ fontWeight: 400 }}>
                                ”). Personally identifiable information may include, but is not limited
                                to:
    </span>
                        </p>
                        <ul style={{ listStyleType: "circle" }}>
                            <li>
                                <span style={{ fontWeight: 400 }}>First name and last name</span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>Email address</span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>Phone number</span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    Address, State, Province, ZIP/Postal code, City
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>Cookies and Usage Data</span>
                            </li>
                        </ul>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                We may use your Personal Data to contact you with newsletters, marketing
                                or promotional materials and other information that may be of interest to
                                you. You may opt out of receiving any, or all, of these communications
                                from us&nbsp;by following the unsubscribe link or by emailing
                                at&nbsp;support@loanith.com.
    </span>
                        </p>
                        <p>
                            <strong>Usage Data</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                We may also collect information that your browser sends whenever you visit
                                our Service or when you access Service by or through a mobile device (“
    </span>
                            <strong>Usage Data</strong>
                            <span style={{ fontWeight: 400 }}>”).</span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                This Usage Data may include information such as your computer's Internet
                                Protocol address (e.g. IP address), browser type, browser version, the
                                pages of our Service that you visit, the time and date of your visit, the
                                time spent on those pages, unique device identifiers and other diagnostic
                                data.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                When you access Service with a mobile device, this Usage Data may include
                                information such as the type of mobile device you use, your mobile device
                                unique ID, the IP address of your mobile device, your mobile operating
                                system, the type of mobile Internet browser you use, unique device
                                identifiers and other diagnostic data.
    </span>
                        </p>
                        <p>
                            <strong>Location Data</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                We may use and store information about your location if you give us
                                permission to do so (“
    </span>
                            <strong>Location Data</strong>
                            <span style={{ fontWeight: 400 }}>
                                ”). We use this data to provide features of our Service, to improve and
                                customize our Service.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                You can enable or disable location services when you use our Service at
                                any time by way of your device settings.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>Tracking Cookies Data</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                We use cookies and similar tracking technologies to track the activity on
                                our Service and we hold certain information.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Cookies are files with a small amount of data which may include an
                                anonymous unique identifier. Cookies are sent to your browser from a
                                website and stored on your device. Other tracking technologies are also
                                used such as beacons, tags and scripts to collect and track information
                                and to improve and analyze our Service.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                You can instruct your browser to refuse all cookies or to indicate when a
                                cookie is being sent. However, if you do not accept cookies, you may not
                                be able to use some portions of our Service.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>Examples of Cookies we use:</span>
                        </p>
                        <p>
                            <strong>Session Cookies:</strong>
                            <span style={{ fontWeight: 400 }}>
                                &nbsp;We use Session Cookies to operate our Service.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>Preference Cookies:</strong>
                            <span style={{ fontWeight: 400 }}>
                                &nbsp;We use Preference Cookies to remember your preferences and various
                                settings.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>Security Cookies:</strong>
                            <span style={{ fontWeight: 400 }}>
                                &nbsp;We use Security Cookies for security purposes.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>Advertising Cookies:</strong>
                            <span style={{ fontWeight: 400 }}>
                                &nbsp;Advertising Cookies are used to serve you with advertisements that
                                may be relevant to you and your interests.
    </span>
                        </p>
                        <p>
                            <strong>Other Data</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                While using our Service, we may also collect the following information:
                                sex, age, date of birth, place of birth, passport details, citizenship,
                                registration at place of residence and actual address, telephone number
                                (work, mobile), details of documents on education, qualification,
                                professional training, employment agreements, non-disclosure agreements,
                                information on bonuses and compensation, information on marital status,
                                family members, social security (or other taxpayer identification) number,
                                office location and other data.&nbsp;
    </span>
                        </p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>Use of Data</strong>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            &nbsp;
    <span style={{ fontWeight: 400 }}>
                                Loanith&nbsp;uses the collected data for various purposes:
    </span>
                        </p>
                        <ol style={{ listStyleType: "lower-roman" }}>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    to provide and maintain our Service;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    to notify you about changes to our Service;&nbsp;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    to allow you to participate in interactive features of our Service when
                                    you choose to do so;&nbsp;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    to provide customer support;&nbsp;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    to gather analysis or valuable information so that we can improve our
                                    Service;&nbsp;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    to monitor the usage of our Service;
      </span>
      &nbsp;
    </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    to detect, prevent and address technical issues;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    to fulfill any other purpose for which you provide it;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    to carry out our obligations and enforce our rights arising from any
                                    contracts entered into between you and us, including for billing and
                                    collection;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    to provide you with notices about your account and/or subscription,
                                    including expiration and renewal notices, email-instructions, etc.;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    to provide you with news, special offers and general information about
                                    other goods, services and events which we offer that are similar to
                                    those that you have already purchased or enquired about unless you have
                                    opted not to receive such information;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    in any other way we may describe when you provide the information;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    for any other purpose with your consent.&nbsp;
      </span>
                            </li>
                        </ol>
                        <ul>
                            <li>
                                <strong>
                                    <strong>Retention of Data</strong>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            &nbsp;
    <span style={{ fontWeight: 400 }}>
                                We will retain your Personal Data only for as long as is necessary for the
                                purposes set out in this Privacy Policy. We will retain and use your
                                Personal Data to the extent necessary to comply with our legal obligations
                                (for example, if we are required to retain your data to comply with
                                applicable laws), resolve disputes, and enforce our legal agreements and
                                policies.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                We will also retain Usage Data for internal analysis purposes. Usage Data
                                is generally retained for a shorter period, except when this data is used
                                to strengthen the security or to improve the functionality of our Service,
                                or we are legally obligated to retain this data for longer time periods.
    </span>
                        </p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>Transfer of Data</strong>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            &nbsp;
    <span style={{ fontWeight: 400 }}>
                                Your information, including Personal Data, may be transferred to – and
                                maintained on – computers located outside of your state, province, country
                                or other governmental jurisdiction where the data protection laws may
                                differ from those of your jurisdiction.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                If you are located outside United States and choose to provide information
                                to us, please note that we transfer the data, including Personal Data, to
                                United States and process it there.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                Your consent to this Privacy Policy followed by your submission of such
                                information represents your agreement to that transfer.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                Loanith&nbsp;will take all the steps reasonably necessary to ensure that
                                your data is treated securely and in accordance with this Privacy Policy
                                and no transfer of your Personal Data will take place to an organisation
                                or a country unless there are adequate controls in place including the
                                security of your data and other personal information.
    </span>
                        </p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>Disclosure of Data</strong>
                                </strong>
                                <strong>&nbsp;</strong>
                            </li>
                        </ul>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                We may disclose personal information that we collect, or you provide:
    </span>
                        </p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>Disclosure for Law Enforcement.</strong>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            &nbsp;
    <span style={{ fontWeight: 400 }}>
                                Under certain circumstances, we may be required to disclose your Personal
                                Data if required to do so by law or in response to valid requests by
                                public authorities.
    </span>
                        </p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>Business Transaction.</strong>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            &nbsp;
    <span style={{ fontWeight: 400 }}>
                                If we or our subsidiaries are involved in a merger, acquisition or asset
                                sale, your Personal Data may be transferred.
    </span>
    &nbsp;
  </p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>Other cases. We may disclose your information also:</strong>
                                </strong>
                            </li>
                        </ul>
                        <ol style={{ listStyleType: "lower-alpha" }}>
                            <li>
                                &nbsp;
      <span style={{ fontWeight: 400 }}>
                                    to our subsidiaries and affiliates;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>&nbsp;</span>
                                <span style={{ fontWeight: 400 }}>
                                    to contractors, service providers, and other third parties we use to
                                    support our business;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>&nbsp;</span>
                                <span style={{ fontWeight: 400 }}>
                                    to fulfill the purpose for which you provide it;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>&nbsp;</span>
                                <span style={{ fontWeight: 400 }}>
                                    for the purpose of including your company’s logo on our website;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>&nbsp;</span>
                                <span style={{ fontWeight: 400 }}>
                                    for any other purpose disclosed by us when you provide the information;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>&nbsp;</span>
                                <span style={{ fontWeight: 400 }}>
                                    with your consent in any other cases;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    if we believe disclosure is necessary or appropriate to protect the
                                    rights, property, or safety of the Company, our customers, or others.
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            </li>
                        </ol>
                        <ul>
                            <li>
                                <strong>
                                    <strong>Security of Data</strong>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            &nbsp;
    <span style={{ fontWeight: 400 }}>
                                The security of your data is important to us but remember that no method
                                of transmission over the Internet or method of electronic storage is 100%
                                secure. While we strive to use commercially acceptable means to protect
                                your Personal Data, we cannot guarantee its absolute security.
    </span>
                        </p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>
                                        Your Data Protection Rights Under General Data Protection Regulation
                                        (GDPR)
        </strong>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            &nbsp;
    <span style={{ fontWeight: 400 }}>
                                If you are a resident of the European Union (EU) and European Economic
                                Area (EEA), you have certain data protection rights, covered by GDPR. –
                                See more at https://eur-lex.europa.eu/eli/reg/2016/679/oj&nbsp;
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                We aim to take reasonable steps to allow you to correct, amend, delete, or
                                limit the use of your Personal Data.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                If you wish to be informed what Personal Data we hold about you and if you
                                want it to be removed from our systems, please email us at
                                support@loanith.com.&nbsp;
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                In certain circumstances, you have the following data protection rights:
    </span>
                        </p>
                        <ol style={{ listStyleType: "lower-roman" }}>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    the right to access, update or to delete the information we have on you;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    the right of rectification. You have the right to have your information
                                    rectified if that information is inaccurate or incomplete;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    the right to object. You have the right to object to our processing of
                                    your Personal Data;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    the right of restriction. You have the right to request that we restrict
                                    the processing of your personal information;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    the right to data portability. You have the right to be provided with a
                                    copy of your Personal Data in a structured, machine-readable and
                                    commonly used format;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    the right to withdraw consent.&nbsp;You also have the right to withdraw
                                    your consent at any time where we rely on your consent to process your
                                    personal information;
      </span>
                            </li>
                        </ol>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                Please note that we may ask you to verify your identity before responding
                                to such requests. Please note, we may not able to provide Service without
                                some necessary data.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                You have the right to complain to a Data Protection Authority about our
                                collection and use of your Personal Data. For more information, please
                                contact your local data protection authority in the European Economic Area
                                (EEA).
    </span>
                        </p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>
                                        Your Data Protection Rights under the California Privacy Protection
                                        Act (CalOPPA)
        </strong>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                CalOPPA is the first state law in the nation to require commercial
                                websites and online services to post a privacy policy. The law’s reach
                                stretches well beyond California to require a person or company in the
                                United States (and conceivable the world) that operates websites
                                collecting personally identifiable information from California consumers
                                to post a conspicuous privacy policy on its website stating exactly the
                                information being collected and those individuals with whom it is being
                                shared, and to comply with this policy. – See more at:
                                https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/&nbsp;
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                According to CalOPPA we agree to the following:
    </span>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                        </p>
                        <ol style={{ listStyleType: "lower-roman" }}>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    users can visit our site anonymously;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    our Privacy Policy link includes the word “Privacy”, and can easily be
                                    found on the page specified above on the home page of our website;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    users will be notified of any privacy policy changes on our Privacy
                                    Policy Page;
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>
                                    users are able to change their personal information by emailing us at
                                    support@loanith.com.&nbsp;
      </span>
                            </li>
                        </ol>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                Our Policy on “Do Not Track” Signals:
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                We honor Do Not Track signals and do not track, plant cookies, or use
                                advertising when a Do Not Track browser mechanism is in place. Do Not
                                Track is a preference you can set in your web browser to inform websites
                                that you do not want to be tracked.&nbsp;
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                You can enable or disable Do Not Track by visiting the Preferences or
                                Settings page of your web browser.
    </span>
                        </p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>
                                        Your Data Protection Rights under the California Consumer Privacy Act
                                        (CCPA)
        </strong>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                If you are a California resident, you are entitled to learn what data we
                                collect about you, ask to delete your data and not to sell (share) it. To
                                exercise your data protection rights, you can make certain requests and
                                ask us:
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>What personal information we have about you</strong>
                            <span style={{ fontWeight: 400 }}>
                                . If you make this request, we will return to you:
    </span>
                        </p>
                        <ol style={{ listStyleType: "lower-roman" }}>
                            <li>
                                <span style={{ fontWeight: 400 }}>&nbsp;</span>
                                <span style={{ fontWeight: 400 }}>
                                    The categories of personal information we have collected about you.
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>&nbsp;</span>
                                <span style={{ fontWeight: 400 }}>
                                    The categories of sources from which we collect your personal
                                    information.
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>&nbsp;</span>
                                <span style={{ fontWeight: 400 }}>
                                    The business or commercial purpose for collecting or selling your
                                    personal information.
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>&nbsp;</span>
                                <span style={{ fontWeight: 400 }}>
                                    The categories of third parties with whom we share personal information.
      </span>
                            </li>
                            <li>
                                <span style={{ fontWeight: 400 }}>&nbsp;</span>
                                <span style={{ fontWeight: 400 }}>
                                    The specific pieces of personal information we have collected about you.
      </span>
                            </li>
                        </ol>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                A list of categories of personal information that we have sold, along with
                                the category of any other company we sold it to. If we have not sold your
                                personal information, we will inform you of that fact.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                A list of categories of personal information that we have disclosed for a
                                business purpose, along with the category of any other company we shared
                                it with.
    </span>
    &nbsp;
  </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Please note, you are entitled to ask us to provide you with this
                                information up to two times in a rolling twelve-month period. When you
                                make this request, the information provided may be limited to the personal
                                information we collected about you in the previous 12&nbsp;months.
    </span>
                        </p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>To delete your personal information</strong>
                                    <span style={{ fontWeight: 400 }}>
                                        . If you make this request, we will delete the personal information we
                                        hold about you as of the date of your request from our records and
                                        direct any service providers to do the same. In some cases, deletion
                                        may be accomplished through de-identification of the information. If
                                        you choose to delete your personal information, you may not be able to
                                        use certain functions that require your personal information to
                                        operate.
        </span>
                                    <strong>&nbsp;</strong>
                                </strong>
      &nbsp;
    </li>
                        </ul>
                        <ul>
                            <li>
                                <strong>
                                    <strong>To stop selling your personal information</strong>
                                    <span style={{ fontWeight: 400 }}>
                                        . We do not sell your personal information for monetary consideration.
                                        However, under some circumstances, a transfer of personal information
                                        to a third party, or within our family of companies, without monetary
                                        consideration may be considered a “sale” under California law.
        </span>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            &nbsp;
    <span style={{ fontWeight: 400 }}>
                                If you submit a request to stop selling your personal information, we will
                                stop making such transfers. If you are a California resident, to opt-out
                                of the sale of your personal information, click “Do Not Sell My Personal
                                Information” at the bottom of our home page to submit your request.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                Please note, if you ask us to delete or stop selling your data, it may
                                impact your experience with us, and you may not be able to participate in
                                certain programs or membership services which require the usage of your
                                personal information to function. But in no circumstances, we will
                                discriminate against you for exercising your rights.
    </span>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                To exercise your California data protection rights described above, please
                                send your request(s) by one of the following means:
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>By email: support@loanith.com</span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                By visiting this page on our website: https://www.loanith.com/contact-us
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>By phone number: +2347031231728</span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                By mail: 1 Raji Abayomi Street, Oshodi, Lagos
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Your data protection rights, described above, are covered by the CCPA,
                                short for the California Consumer Privacy Act. To find out more, visit the
                                official California Legislative Information website. The CCPA took effect
                                on 01/01/2020.&nbsp;
    </span>
                        </p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>Service Providers</strong>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            &nbsp;
    <span style={{ fontWeight: 400 }}>
                                We may employ third party companies and individuals to facilitate our
                                Service (“
    </span>
                            <strong>Service Providers</strong>
                            <span style={{ fontWeight: 400 }}>
                                ”), provide Service on our behalf, perform Service-related services or
                                assist us in analysing how our Service is used.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                These third parties have access to your Personal Data only to perform
                                these tasks on our behalf and are obligated not to disclose or use it for
                                any other purpose.
    </span>
                        </p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>Analytics</strong>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            &nbsp;
    <span style={{ fontWeight: 400 }}>
                                We may use third-party Service Providers to monitor and analyze the use of
                                our Service.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>Google Analytics</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Google Analytics is a web analytics service offered by Google that tracks
                                and reports website traffic. Google uses the data collected to track and
                                monitor the use of our Service. This data is shared with other Google
                                services. Google may use the collected data to contextualise and
                                personalise the ads of its own advertising network.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                For more information on the privacy practices of Google, please visit the
                                Google Privacy Terms web page: https://policies.google.com/privacy?hl=en
    </span>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                We also encourage you to review the Google's policy for safeguarding your
                                data: https://support.google.com/analytics/answer/6004245.
    </span>
                        </p>
                        <p>
                            <strong>Firebase</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Firebase is analytics service provided by Google Inc.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                You may opt-out of certain Firebase features through your mobile device
                                settings, such as your device advertising settings or by following the
                                instructions provided by Google in their Privacy Policy:
                                https://policies.google.com/privacy?hl=en
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                For more information on what type of information Firebase collects, please
                                visit the Google Privacy Terms web page:
                                https://policies.google.com/privacy?hl=en
    </span>
                        </p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>CI/CD tools</strong>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                We may use third-party Service Providers to automate the development
                                process of our Service.&nbsp;
    </span>
                        </p>
                        <p>
                            <strong>GitHub</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>GitHub is provided by GitHub, Inc.</span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                GitHub is a development platform to host and review code, manage projects,
                                and build software.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                For more information on what data GitHub collects for what purpose and how
                                the protection of the data is ensured, please visit GitHub Privacy Policy
                                page:
    </span>{" "}
                            <a href="https://help.github.com/en/articles/github-privacy-statement">
                                <span style={{ fontWeight: 400 }}>
                                    https://help.github.com/en/articles/github-privacy-statement.
      </span>
                            </a>
                        </p>
                        <p>
                            <strong>GitLab CI/CD</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                GitLab CI/CD is provided by GitLab, Inc.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                GitLab CI (Continuous Integration) service is a part of GitLab that build
                                and test the software whenever developer pushes code to application.&nbsp;
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                GitLab CD (Continuous Deployment) is a software service that places the
                                changes of every code in the production which results in every day
                                deployment of production.&nbsp;
    </span>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                For more information on what data GitLab CI/CD collects for what purpose
                                and how the protection of the data is ensured, please visit GitLab CI/CD
                                Privacy Policy page: https://about.gitlab.com/privacy/.
    </span>
                        </p>
                        <p>
                            <strong>Travis CI</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Travis CI is a distributed continuous integration service to build and
                                test projects hosted at GitHub.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                For more information on what data Travis CI collects for what purpose and
                                how the protection of the data is ensured, please visit Travis CI Privacy
                                Policy page: https://docs.travis-ci.com/legal/privacy-policy.
    </span>
                        </p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>Behavioral Remarketing</strong>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Loanith&nbsp;uses remarketing services to advertise on third party
                                websites to you after you visited our Service. We and our third-party
                                vendors use cookies to inform, optimise and serve ads based on your past
                                visits to our Service.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>Google Ads (AdWords)</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Google Ads (AdWords) remarketing service is provided by Google Inc.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                You can opt-out of Google Analytics for Display Advertising and customize
                                the Google Display Network ads by visiting the Google Ads Settings page:
                                http://www.google.com/settings/ads
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Google also recommends installing the Google Analytics Opt-out Browser
                                Add-on – https://tools.google.com/dlpage/gaoptout – for your web browser.
                                Google Analytics Opt-out Browser Add-on provides visitors with the ability
                                to prevent their data from being collected and used by Google Analytics.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                For more information on the privacy practices of Google, please visit the
                                Google Privacy Terms web page: https://policies.google.com/privacy?hl=en
    </span>
                        </p>
                        <p>
                            <strong>&nbsp;</strong>
                            <strong>Bing Ads Remarketing</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Bing Ads remarketing service is provided by Microsoft Inc.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                You can opt-out of Bing Ads interest-based ads by following their
                                instructions:
                                https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                You can learn more about the privacy practices and policies of Microsoft
                                by visiting their Privacy Policy page:
                                https://privacy.microsoft.com/en-us/PrivacyStatement
    </span>
                        </p>
                        <p>
                            <strong>&nbsp;</strong>
                            <strong>Twitter</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Twitter remarketing service is provided by Twitter Inc.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                You can opt-out from Twitter's interest-based ads by following their
                                instructions: https://support.twitter.com/articles/20170405
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                You can learn more about the privacy practices and policies of Twitter by
                                visiting their Privacy Policy page: https://twitter.com/privacy
    </span>
                        </p>
                        <p>
                            <strong>&nbsp;</strong>
                            <strong>Facebook</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Facebook remarketing service is provided by Facebook Inc.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                You can learn more about interest-based advertising from Facebook by
                                visiting this page: https://www.facebook.com/help/164968693837950
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                To opt-out from Facebook's interest-based ads, follow these instructions
                                from Facebook: https://www.facebook.com/help/568137493302217
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                Facebook adheres to the Self-Regulatory Principles for Online Behavioural
                                Advertising established by the Digital Advertising Alliance. You can also
                                opt-out from Facebook and other participating companies through the
                                Digital Advertising Alliance in the USA http://www.aboutads.info/choices/,
                                the Digital Advertising Alliance of Canada in Canada
                                http://youradchoices.ca/ or the European Interactive Digital Advertising
                                Alliance in Europe http://www.youronlinechoices.eu/, or opt-out using your
                                mobile device settings.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                For more information on the privacy practices of Facebook, please visit
                                Facebook's Data Policy: https://www.facebook.com/privacy/explanation
    </span>
                        </p>
                        <p>
                            <strong>&nbsp;</strong>
                            <strong>Pinterest</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Pinterest remarketing service is provided by Pinterest Inc.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                You can opt-out from Pinterest's interest-based ads by enabling the “Do
                                Not Track” functionality of your web browser or by following Pinterest
                                instructions:
                                http://help.pinterest.com/en/articles/personalization-and-data
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                You can learn more about the privacy practices and policies of Pinterest
                                by visiting their Privacy Policy page:
                                https://about.pinterest.com/en/privacy-policy
    </span>
                        </p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>Payments</strong>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                We may provide paid products and/or services within Service. In that case,
                                we use third-party services for payment processing (e.g. payment
                                processors).
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                We will not store or collect your payment card details. That information
                                is provided directly to our third-party payment processors whose use of
                                your personal information is governed by their Privacy Policy. These
                                payment processors adhere to the standards set by PCI-DSS as managed by
                                the PCI Security Standards Council, which is a joint effort of brands like
                                Visa, Mastercard, American Express and Discover. PCI-DSS requirements help
                                ensure the secure handling of payment information.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                The payment processors we work with are:
    </span>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                        </p>
                        <p>
                            <strong>PayPal or Braintree:</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Their Privacy Policy can be viewed
                                at&nbsp;https://www.paypal.com/webapps/mpp/ua/privacy-full
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>FastSpring:</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Their Privacy Policy can be viewed at&nbsp;http://fastspring.com/privacy/
    </span>
                        </p>
                        <p>
                            <strong>Apple Store In-App Payments:</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Their Privacy Policy can be viewed at:
                                https://www.apple.com/legal/privacy/en-ww/ /
                                https://support.apple.com/en-us/HT203027&nbsp;
    </span>
                        </p>
                        <p>
                            <strong>Google Play In-App Payments:</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Their Privacy Policy can be viewed at:
                                https://policies.google.com/privacy?hl=en&amp;gl=us /
                                https://payments.google.com/payments/apis-secure/u/0/get_legal_document?ldo=0&amp;ldt=privacynotice&amp;ldl=en&nbsp;
    </span>
                        </p>
                        <p>
                            <strong>Stripe:</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Their Privacy Policy can be viewed at: https://stripe.com/us/privacy
    </span>
                        </p>
                        <p>
                            <strong>2Checkout:</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Their Privacy Policy can be viewed at:
                                https://www.2checkout.com/legal/privacy/&nbsp;
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>Adyen:</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Their Terms and conditions can be viewed at
                                https://www.adyen.com/legal/terms-and-conditions.
    </span>
                        </p>
                        <p>
                            <strong>Alipay:</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Their Privacy Policy can be viewed at:
                                https://render.alipay.com/p/f/agreementpages/alipayglobalprivacypolicy.html&nbsp;
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>Authorize.net:</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Their Privacy Policy can be viewed at:
                                https://www.authorize.net/about-us/privacy/&nbsp;
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>Elavon:</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Their Privacy Policy can be viewed at:
                                https://www.elavon.com/privacy-pledge.html&nbsp;
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>First Data:</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Their Privacy Policy can be viewed
                                at:&nbsp;https://www.firstdata.com/en_us/privacy.html&nbsp;
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>Go Cardless:</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Their Privacy Policy can be viewed at:
                                https://gocardless.com/legal/privacy&nbsp;
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>Klarna:</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Their Services Terms, Privacy Policy and Buyer Protection Policy can be
                                viewed at https://www.klarna.com/us/legal/.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>Moneris:</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Their Privacy Policy can be viewed at:
                                https://www.moneris.com/legal/privacy-policy&nbsp;
    </span>
                        </p>
                        <p>
                            <strong>&nbsp;</strong>
                            <strong>Plaid:</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Their End User Privacy Policy, Cookie Policy and Privacy Statement can be
                                viewed at https://plaid.com/legal/.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>Sage Pay:</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Their Privacy Policy can be viewed at:
                                https://www.sagepay.co.uk/policies/privacy-policy&nbsp;
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>Square:</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Their Privacy Policy can be viewed at:
                                https://squareup.com/us/en/legal/general/privacy&nbsp;
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>Verifone:</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Their Privacy Policy can be viewed at:
                                https://www.verifone.com/en/privacy&nbsp;
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>WePay:</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Their Privacy Policy can be viewed at:
                                https://go.wepay.com/privacy-policy&nbsp;
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>WorldPay:</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Their Privacy Policy can be viewed at:
                                https://online.worldpay.com/terms/privacy&nbsp;
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <strong>WeChat:</strong>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                Their Privacy Policy can be viewed at:
                                https://www.wechat.com/en/privacy_policy.html&nbsp;
    </span>
                        </p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>Links to Other Sites</strong>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            &nbsp;
    <span style={{ fontWeight: 400 }}>
                                Our Service may contain links to other sites that are not operated by us.
                                If you click a third party link, you will be directed to that third
                                party's site. We strongly advise you to review the Privacy Policy of every
                                site you visit.
    </span>
                        </p>
                        <p>
                            <strong>&nbsp;</strong>
                            <span style={{ fontWeight: 400 }}>
                                We have no control over and assume no responsibility for the content,
                                privacy policies or practices of any third party sites or services.
    </span>
                        </p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>Children's Privacy</strong>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            &nbsp;
    <span style={{ fontWeight: 400 }}>
                                Our Services are not intended for use by children under the age of 18 (“
    </span>
                            <strong>Child</strong>
                            <span style={{ fontWeight: 400 }}>” or “</span>
                            <strong>Children</strong>
                            <span style={{ fontWeight: 400 }}>”).&nbsp;</span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                We do not knowingly collect personally identifiable information from
                                Children under 18. If you become aware that a Child has provided us with
                                Personal Data, please contact us. If we become aware that we have
                                collected Personal Data from Children without verification of parental
                                consent, we take steps to remove that information from our servers.
    </span>
                        </p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>Changes to This Privacy Policy</strong>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                We may update our Privacy Policy from time to time. We will notify you of
                                any changes by posting the new Privacy Policy on this page.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>
                                We will let you know via email and/or a prominent notice on our Service,
                                prior to the change becoming effective and update “effective date” at the
                                top of this Privacy Policy.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                You are advised to review this Privacy Policy periodically for any
                                changes. Changes to this Privacy Policy are effective when they are posted
                                on this page.
    </span>
                        </p>
                        <ul>
                            <li>
                                <strong>
                                    <strong>Contact Us</strong>
                                </strong>
                            </li>
                        </ul>
                        <p>
                            &nbsp;
    <span style={{ fontWeight: 400 }}>
                                If you have any questions about this Privacy Policy, please contact us:
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>By email: support@loanith.com.</span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                By visiting this page on our website: https://www.loanith.com/contact-us.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>By phone number: +2347031231728.</span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                            <span style={{ fontWeight: 400 }}>
                                By mail: 1 Raji Abayomi Street, Oshodi, Lagos.
    </span>
                        </p>
                        <p>
                            <span style={{ fontWeight: 400 }}>&nbsp;</span>
                        </p>
                    </div>

                </div>
            </div>

        </div>
    )
}

export default PrivacyPolicy;